{{- $root := . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "generator.name" $root }}-docker-config
  labels: {{- include "generator.labels" $root | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "generator.imagePullSecret" $root }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "generator.labels" . | nindent 4 }}
  name: {{ template "generator.name" . }}
type: Opaque
data:
{{- range $idx, $secret := $root.Values.secretEnv }}
  {{ $secret.name }}: |- {{ tpl $secret.value $root | b64enc | nindent 4 }}
{{- end }}
{{- range $key, $data := $root.Values.secretFiles }}
  {{ $key }}: |- {{ tpl $data $root | b64enc | nindent 4 }}
{{- end }}

