kind: Service
apiVersion: v1
metadata:
  name: {{ template "generator.name" . }}
  labels: {{- include "generator.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations -}}
    {{- tpl (toYaml .) $ | nindent 4 -}}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    deployment: {{ template "generator.name" . }}
  ports:
    {{- range $index, $port := $.Values.service.ports }}
    - protocol: TCP
      name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
    {{- end }}