FROM ubuntu
ARG required_arg
ARG module
ARG optional_arg="val"

RUN echo "OK \n \
        OK new line \n \
        OK new line2 \
    "
RUN echo "OK: ${required_arg}: ${optional_arg}: module=${module}"
