image:
  tag: latest
  repo: docker.simple-container.com/dev/welder/welder-docs
deployment:
  replicaCount: 1
  maxSurge: 1
  maxUnavailable: 0
  containerPort: 80
service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
podAnnotations:
  timestamp: "{{ date \"20060102150405\" .Release.Time }}"